"""
    Use these functions to hash the passwords or validation user given password with stored one;
"""
import bcrypt

def hashpw(password : str) -> str:
    """ Returns a hashed password"""

    return bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')

def checkpw(password : str, hashed_password : str) -> bool:
    """ Returns True if hashed_password was generated by password"""

    return bcrypt.checkpw(password.encode('utf-8'), hashed_password.encode('utf-8'))