export const doctorService = {
    getDoctors(){
        return [
            // Delhi - 110001
            {
                "ez_id": "D001",
                "role": "doctor",
                "name": "Dr. Rajesh Kumar",
                "specialization": "Cardiologist",
                "qualification": "MBBS, MD Cardiology",
                "experience": "15 years",
                "hospital": "City Care Hospital",
                "address": "123 Main Road, Shanti Nagar, Delhi",
                "pincode": "110001",
                "phone": "+91-9876543210",
                "email": "dr.rajesh@citycarehospital.com",
                "consultation_fee": "₹800",
                "timings": "10:00 AM - 6:00 PM",
                "availability": ["Monday", "Tuesday", "Wednesday", "Friday", "Saturday"]
            },
            {
                "ez_id": "D002",
                "role": "doctor",
                "name": "Dr. Priya Sharma",
                "specialization": "Pediatrician",
                "qualification": "MBBS, MD Pediatrics",
                "experience": "12 years",
                "hospital": "Green Valley Clinic",
                "address": "45 Green Park, South Delhi",
                "pincode": "110001",
                "phone": "+91-9811122233",
                "email": "dr.priya@greenvalleyclinic.in",
                "consultation_fee": "₹600",
                "timings": "9:00 AM - 5:00 PM",
                "availability": ["Monday", "Tuesday", "Thursday", "Friday", "Saturday"]
            },
            {
                "ez_id": "D003",
                "role": "doctor",
                "name": "Dr. Amit Singh",
                "specialization": "Neurologist",
                "qualification": "MBBS, DM Neurology",
                "experience": "18 years",
                "hospital": "Sunrise Hospital",
                "address": "78 Sunrise Road, Central Delhi",
                "pincode": "110001",
                "phone": "+91-9999988888",
                "email": "dr.amit@sunrisehospitals.com",
                "consultation_fee": "₹1200",
                "timings": "11:00 AM - 7:00 PM",
                "availability": ["Monday", "Wednesday", "Thursday", "Friday"]
            },
            {
                "ez_id": "D004",
                "role": "doctor",
                "name": "Dr. Sunita Gupta",
                "specialization": "Gynecologist",
                "qualification": "MBBS, MS Gynecology",
                "experience": "14 years",
                "hospital": "Life Line Hospital",
                "address": "23 Ashok Vihar, Delhi",
                "pincode": "110001",
                "phone": "+91-9898989898",
                "email": "dr.sunita@lifeline.com",
                "consultation_fee": "₹700",
                "timings": "2:00 PM - 8:00 PM",
                "availability": ["Tuesday", "Wednesday", "Thursday", "Saturday", "Sunday"]
            },
            {
                "ez_id": "D005",
                "role": "doctor",
                "name": "Dr. Vikram Malhotra",
                "specialization": "Orthopedist",
                "qualification": "MBBS, MS Orthopedics",
                "experience": "20 years",
                "hospital": "Hopewell Medical Center",
                "address": "Plot 54, Karol Bagh, Delhi",
                "pincode": "110001",
                "phone": "+91-9312345678",
                "email": "dr.vikram@hopewellmed.com",
                "consultation_fee": "₹900",
                "timings": "10:00 AM - 4:00 PM",
                "availability": ["Monday", "Tuesday", "Friday", "Saturday"]
            },
            {
                "ez_id": "D006",
                "role": "doctor",
                "name": "Dr. Kavita Jain",
                "specialization": "Dermatologist",
                "qualification": "MBBS, MD Dermatology",
                "experience": "10 years",
                "hospital": "Delhi Skin Clinic",
                "address": "56 CP, Connaught Place, Delhi",
                "pincode": "110001",
                "phone": "+91-9876512345",
                "email": "dr.kavita@delhiskin.com",
                "consultation_fee": "₹650",
                "timings": "12:00 PM - 6:00 PM",
                "availability": ["Monday", "Wednesday", "Friday", "Saturday"]
            },

            // Noida - 201301
            {
                "ez_id": "D007",
                "role": "doctor",
                "name": "Dr. Rohit Agarwal",
                "specialization": "Cardiologist",
                "qualification": "MBBS, DM Cardiology",
                "experience": "16 years",
                "hospital": "Fortune Hospital",
                "address": "12 Block B, Noida Sector 62",
                "pincode": "201301",
                "phone": "+91-9123456789",
                "email": "dr.rohit@fortunehospital.com",
                "consultation_fee": "₹1000",
                "timings": "9:00 AM - 5:00 PM",
                "availability": ["Monday", "Tuesday", "Wednesday", "Thursday", "Saturday"]
            },
            {
                "ez_id": "D008",
                "role": "doctor",
                "name": "Dr. Meera Verma",
                "specialization": "Pediatrician",
                "qualification": "MBBS, MD Pediatrics",
                "experience": "11 years",
                "hospital": "Noida City Clinic",
                "address": "A-34, Sector 15, Noida",
                "pincode": "201301",
                "phone": "+91-9876543219",
                "email": "dr.meera@noidaclinic.com",
                "consultation_fee": "₹550",
                "timings": "8:00 AM - 2:00 PM",
                "availability": ["Monday", "Tuesday", "Thursday", "Friday", "Saturday"]
            },
            {
                "ez_id": "D009",
                "role": "doctor",
                "name": "Dr. Anuj Saxena",
                "specialization": "General Surgeon",
                "qualification": "MBBS, MS Surgery",
                "experience": "13 years",
                "hospital": "Metro Medical Center",
                "address": "32 Metro Tower, Noida",
                "pincode": "201301",
                "phone": "+91-9000000001",
                "email": "dr.anuj@metrocenter.com",
                "consultation_fee": "₹800",
                "timings": "10:00 AM - 6:00 PM",
                "availability": ["Monday", "Wednesday", "Thursday", "Friday"]
            },
            {
                "ez_id": "D010",
                "role": "doctor",
                "name": "Dr. Pooja Mittal",
                "specialization": "Oncologist",
                "qualification": "MBBS, DM Oncology",
                "experience": "17 years",
                "hospital": "HealCare Hospital",
                "address": "Green Tower, Sector 50, Noida",
                "pincode": "201301",
                "phone": "+91-9000000002",
                "email": "dr.pooja@healcare.org",
                "consultation_fee": "₹1500",
                "timings": "11:00 AM - 7:00 PM",
                "availability": ["Tuesday", "Wednesday", "Thursday", "Saturday"]
            },
            {
                "ez_id": "D011",
                "role": "doctor",
                "name": "Dr. Deepak Chopra",
                "specialization": "Dentist",
                "qualification": "BDS, MDS",
                "experience": "9 years",
                "hospital": "Wellness Point",
                "address": "C-87, Sector 61, Noida",
                "pincode": "201301",
                "phone": "+91-9000000003",
                "email": "dr.deepak@wellness.com",
                "consultation_fee": "₹500",
                "timings": "10:00 AM - 6:00 PM",
                "availability": ["Monday", "Tuesday", "Wednesday", "Friday", "Saturday"]
            },
            {
                "ez_id": "D012",
                "role": "doctor",
                "name": "Dr. Nisha Kapoor",
                "specialization": "Gynecologist",
                "qualification": "MBBS, MS Gynecology",
                "experience": "12 years",
                "hospital": "Noida Women's Clinic",
                "address": "B-45, Sector 18, Noida",
                "pincode": "201301",
                "phone": "+91-9876000001",
                "email": "dr.nisha@noidawomen.com",
                "consultation_fee": "₹750",
                "timings": "3:00 PM - 9:00 PM",
                "availability": ["Monday", "Tuesday", "Thursday", "Friday", "Sunday"]
            },

            // Ghaziabad - 201010
            {
                "ez_id": "D013",
                "role": "doctor",
                "name": "Dr. Suresh Khanna",
                "specialization": "Cardiologist",
                "qualification": "MBBS, MD Cardiology",
                "experience": "19 years",
                "hospital": "Ghaziabad Central Hospital",
                "address": "NH-24, Indirapuram, Ghaziabad",
                "pincode": "201010",
                "phone": "+91-9876512345",
                "email": "dr.suresh@ghzbmed.com",
                "consultation_fee": "₹950",
                "timings": "9:00 AM - 5:00 PM",
                "availability": ["Monday", "Tuesday", "Wednesday", "Friday", "Saturday"]
            },
            {
                "ez_id": "D014",
                "role": "doctor",
                "name": "Dr. Rekha Agarwal",
                "specialization": "Physiotherapist",
                "qualification": "BPT, MPT",
                "experience": "8 years",
                "hospital": "Vivekanand Hospital",
                "address": "Plot 98, Vasundhara, Ghaziabad",
                "pincode": "201010",
                "phone": "+91-9876500001",
                "email": "dr.rekha@vivek.com",
                "consultation_fee": "₹400",
                "timings": "8:00 AM - 4:00 PM",
                "availability": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
            },
            {
                "ez_id": "D015",
                "role": "doctor",
                "name": "Dr. Manoj Kumar",
                "specialization": "Neurologist",
                "qualification": "MBBS, DM Neurology",
                "experience": "21 years",
                "hospital": "Sarvoday Health Hub",
                "address": "B-76, Rajnagar Extension, Ghaziabad",
                "pincode": "201010",
                "phone": "+91-9876500002",
                "email": "dr.manoj@sarvoday.org",
                "consultation_fee": "₹1300",
                "timings": "10:00 AM - 6:00 PM",
                "availability": ["Monday", "Wednesday", "Thursday", "Friday"]
            },
            {
                "ez_id": "D016",
                "role": "doctor",
                "name": "Dr. Sanjay Khanna",
                "specialization": "ENT Specialist",
                "qualification": "MBBS, MS ENT",
                "experience": "14 years",
                "hospital": "Dr. Khanna's Clinic",
                "address": "C-12, Patel Nagar, Ghaziabad",
                "pincode": "201010",
                "phone": "+91-9876500003",
                "email": "dr.sanjay@khannaclinic.in",
                "consultation_fee": "₹600",
                "timings": "9:00 AM - 3:00 PM",
                "availability": ["Monday", "Tuesday", "Thursday", "Saturday"]
            },
            {
                "ez_id": "D017",
                "role": "doctor",
                "name": "Dr. Smita Joshi",
                "specialization": "General Surgeon",
                "qualification": "MBBS, MS Surgery",
                "experience": "16 years",
                "hospital": "Care & Cure Hospital",
                "address": "87 Shakti Khand, Ghaziabad",
                "pincode": "201010",
                "phone": "+91-9876500004",
                "email": "dr.smita@carecure.in",
                "consultation_fee": "₹850",
                "timings": "11:00 AM - 7:00 PM",
                "availability": ["Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
            },
            {
                "ez_id": "D018",
                "role": "doctor",
                "name": "Dr. Anil Sharma",
                "specialization": "General Medicine",
                "qualification": "MBBS, MD Medicine",
                "experience": "22 years",
                "hospital": "Ghaziabad Health Center",
                "address": "Kavi Nagar, Ghaziabad",
                "pincode": "201010",
                "phone": "+91-9876500005",
                "email": "dr.anil@ghzhealth.com",
                "consultation_fee": "₹500",
                "timings": "8:00 AM - 8:00 PM",
                "availability": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
            },

            // Ghaziabad - 201011
            {
                "ez_id": "D019",
                "role": "doctor",
                "name": "Dr. Rakesh Tiwari",
                "specialization": "Orthopedist",
                "qualification": "MBBS, MS Orthopedics",
                "experience": "18 years",
                "hospital": "Bone Care Clinic",
                "address": "Mohan Nagar, Ghaziabad",
                "pincode": "201011",
                "phone": "+91-9876600001",
                "email": "dr.rakesh@bonecare.com",
                "consultation_fee": "₹900",
                "timings": "10:00 AM - 6:00 PM",
                "availability": ["Monday", "Tuesday", "Wednesday", "Friday", "Saturday"]
            },
            {
                "ez_id": "D020",
                "role": "doctor",
                "name": "Dr. Neetu Garg",
                "specialization": "Pediatrician",
                "qualification": "MBBS, MD Pediatrics",
                "experience": "13 years",
                "hospital": "Kids Care Hospital",
                "address": "Sahibabad, Ghaziabad",
                "pincode": "201011",
                "phone": "+91-9876600002",
                "email": "dr.neetu@kidscare.com",
                "consultation_fee": "₹600",
                "timings": "9:00 AM - 5:00 PM",
                "availability": ["Monday", "Tuesday", "Thursday", "Friday", "Saturday", "Sunday"]
            },
            {
                "ez_id": "D021",
                "role": "doctor",
                "name": "Dr. Ashok Verma",
                "specialization": "Dermatologist",
                "qualification": "MBBS, MD Dermatology",
                "experience": "15 years",
                "hospital": "Skin Solutions",
                "address": "Raj Nagar, Ghaziabad",
                "pincode": "201011",
                "phone": "+91-9876600003",
                "email": "dr.ashok@skinsolutions.com",
                "consultation_fee": "₹700",
                "timings": "11:00 AM - 7:00 PM",
                "availability": ["Monday", "Wednesday", "Thursday", "Friday", "Saturday"]
            },
            {
                "ez_id": "D022",
                "role": "doctor",
                "name": "Dr. Vandana Singh",
                "specialization": "Gynecologist",
                "qualification": "MBBS, MS Gynecology",
                "experience": "17 years",
                "hospital": "Women's Health Clinic",
                "address": "Govind Puram, Ghaziabad",
                "pincode": "201011",
                "phone": "+91-9876600004",
                "email": "dr.vandana@womenshealth.com",
                "consultation_fee": "₹800",
                "timings": "2:00 PM - 8:00 PM",
                "availability": ["Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
            },
            {
                "ez_id": "D023",
                "role": "doctor",
                "name": "Dr. Ravi Kumar",
                "specialization": "Psychiatrist",
                "qualification": "MBBS, MD Psychiatry",
                "experience": "12 years",
                "hospital": "Mind Care Center",
                "address": "Crossings Republik, Ghaziabad",
                "pincode": "201011",
                "phone": "+91-9876600005",
                "email": "dr.ravi@mindcare.com",
                "consultation_fee": "₹1000",
                "timings": "10:00 AM - 6:00 PM",
                "availability": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
            },
            {
                "ez_id": "D024",
                "role": "doctor",
                "name": "Dr. Preeti Agarwal",
                "specialization": "Ophthalmologist",
                "qualification": "MBBS, MS Ophthalmology",
                "experience": "11 years",
                "hospital": "Eye Care Center",
                "address": "Vaishali, Ghaziabad",
                "pincode": "201011",
                "phone": "+91-9876600006",
                "email": "dr.preeti@eyecare.com",
                "consultation_fee": "₹750",
                "timings": "9:00 AM - 5:00 PM",
                "availability": ["Monday", "Tuesday", "Thursday", "Friday", "Saturday"]
            },

            // Rohini Delhi - 110085
            {
                "ez_id": "D025",
                "role": "doctor",
                "name": "Dr. Hemant Jain",
                "specialization": "Gynecologist",
                "qualification": "MBBS, MS Gynecology",
                "experience": "16 years",
                "hospital": "Nirman Medical Center",
                "address": "Sector 3, Rohini, Delhi",
                "pincode": "110085",
                "phone": "+91-9958000011",
                "email": "dr.hemant@nirmanmed.in",
                "consultation_fee": "₹750",
                "timings": "9:00 AM - 5:00 PM",
                "availability": ["Monday", "Tuesday", "Wednesday", "Friday", "Saturday"]
            },
            {
                "ez_id": "D026",
                "role": "doctor",
                "name": "Dr. Arun Malhotra",
                "specialization": "Nephrologist",
                "qualification": "MBBS, DM Nephrology",
                "experience": "20 years",
                "hospital": "Rohini Super Hospital",
                "address": "Plot 4, Rohini Sec 9, Delhi",
                "pincode": "110085",
                "phone": "+91-9958000012",
                "email": "dr.arun@superrohini.com",
                "consultation_fee": "₹1200",
                "timings": "10:00 AM - 6:00 PM",
                "availability": ["Monday", "Wednesday", "Thursday", "Friday"]
            },
            {
                "ez_id": "D027",
                "role": "doctor",
                "name": "Dr. Seema Kapoor",
                "specialization": "Dermatologist",
                "qualification": "MBBS, MD Dermatology",
                "experience": "14 years",
                "hospital": "Sunbeam Hospital",
                "address": "Sunbeam Marg, Rohini, Delhi",
                "pincode": "110085",
                "phone": "+91-9958000013",
                "email": "dr.seema@sunbeam.com",
                "consultation_fee": "₹650",
                "timings": "11:00 AM - 7:00 PM",
                "availability": ["Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
            },
            {
                "ez_id": "D028",
                "role": "doctor",
                "name": "Dr. Rahul Gupta",
                "specialization": "Pediatrician",
                "qualification": "MBBS, MD Pediatrics",
                "experience": "9 years",
                "hospital": "Rohini Clinic Plus",
                "address": "B-23, Sector 7, Rohini, Delhi",
                "pincode": "110085",
                "phone": "+91-9958000014",
                "email": "dr.rahul@clinicplus.in",
                "consultation_fee": "₹500",
                "timings": "10:00 AM - 6:00 PM",
                "availability": ["Monday", "Tuesday", "Wednesday", "Thursday", "Saturday"]
            },
            {
                "ez_id": "D029",
                "role": "doctor",
                "name": "Dr. Shilpa Aggarwal",
                "specialization": "Diabetologist",
                "qualification": "MBBS, MD Medicine",
                "experience": "13 years",
                "hospital": "Rohini Family Health Center",
                "address": "B-67, Sec 8, Rohini, Delhi",
                "pincode": "110085",
                "phone": "+91-9958000015",
                "email": "dr.shilpa@familycare.org",
                "consultation_fee": "₹600",
                "timings": "8:00 AM - 4:00 PM",
                "availability": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
            },

            // East Delhi - 110053
            {
                "ez_id": "D030",
                "role": "doctor",
                "name": "Dr. Ajay Sharma",
                "specialization": "Cardiologist",
                "qualification": "MBBS, DM Cardiology",
                "experience": "18 years",
                "hospital": "East Delhi Medcare",
                "address": "C-2 Yamuna Vihar, Delhi",
                "pincode": "110053",
                "phone": "+91-9012345678",
                "email": "dr.ajay@eastdelhi.com",
                "consultation_fee": "₹1000",
                "timings": "9:00 AM - 5:00 PM",
                "availability": ["Monday", "Tuesday", "Wednesday", "Thursday", "Saturday"]
            },
            {
                "ez_id": "D031",
                "role": "doctor",
                "name": "Dr. Sushma Rani",
                "specialization": "ENT Specialist",
                "qualification": "MBBS, MS ENT",
                "experience": "12 years",
                "hospital": "Yamuna PolyClinic",
                "address": "Block D, Yamuna Vihar, Delhi",
                "pincode": "110053",
                "phone": "+91-9012345679",
                "email": "dr.sushma@yamunapoly.com",
                "consultation_fee": "₹550",
                "timings": "9:00 AM - 5:00 PM",
                "availability": ["Monday", "Tuesday", "Thursday", "Friday", "Saturday"]
            },
            {
                "ez_id": "D032",
                "role": "doctor",
                "name": "Dr. Vinod Kumar",
                "specialization": "General Medicine",
                "qualification": "MBBS, MD Medicine",
                "experience": "25 years",
                "hospital": "Swasthya Hospital",
                "address": "E-5, Shahdara, Delhi",
                "pincode": "110053",
                "phone": "+91-9012345680",
                "email": "dr.vinod@swasthya.com",
                "consultation_fee": "₹450",
                "timings": "8:00 AM - 8:00 PM",
                "availability": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
            },
            {
                "ez_id": "D033",
                "role": "doctor",
                "name": "Dr. Neha Sachdeva",
                "specialization": "Cardiac Surgeon",
                "qualification": "MBBS, MCh Cardiac Surgery",
                "experience": "16 years",
                "hospital": "Delhi Heart Point",
                "address": "L-12, Krishna Nagar, Delhi",
                "pincode": "110053",
                "phone": "+91-9012345681",
                "email": "dr.neha@heartpoint.com",
                "consultation_fee": "₹2000",
                "timings": "10:00 AM - 4:00 PM",
                "availability": ["Tuesday", "Wednesday", "Thursday", "Friday"]
            },
            {
                "ez_id": "D034",
                "role": "doctor",
                "name": "Dr. Ramesh Chand",
                "specialization": "Diabetologist",
                "qualification": "MBBS, MD Medicine",
                "experience": "20 years",
                "hospital": "Shakti Clinic",
                "address": "E-89, Yamuna Vihar, Delhi",
                "pincode": "110053",
                "phone": "+91-9012345682",
                "email": "dr.ramesh@shakticlinic.org",
                "consultation_fee": "₹500",
                "timings": "10:00 AM - 4:00 PM",
                "availability": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
            }
        ]
    },

    getDoctorList(pincode) {
        return Promise.resolve(
        this.getDoctors().filter(doctor => doctor["pincode"] === pincode)
        );
    },
    getDoctor(query) {
        if (query['email']){
            return Promise.resolve(
                this.getDoctors().find(doctor => doctor["email"] === query['email'])
            );
        }
        else if (query['ez_id']){
            return Promise.resolve(
                this.getDoctors().find(doctor => doctor["ez_id"] === query['ez_id'])
            );
        }
        return Promise.resolve(null);
    },
}
