export const hospitalService = {
    getHospitals(){
        return [
            {
                "hospital_id": "H001",
                "name": "City Care Hospital",
                "address": "123 Main Road, Shanti Nagar, Delhi",
                "pincode": "110001",
                "phone": "+91-9876543210",
                "email": "contact@citycarehospital.com",
                "type": "Multi-specialty",
                "beds": 150,
                "services": ["Emergency", "Cardiology", "Orthopedics", "Radiology", "Pharmacy"],
                "timings": "24/7",
                "coordinates": { "lat": 28.6139, "lng": 77.2090 }
            },
            {
                "hospital_id": "H002",
                "name": "Green Valley Clinic",
                "address": "45 Green Park, South Delhi",
                "pincode": "110001",
                "phone": "+91-9811122233",
                "email": "info@greenvalleyclinic.in",
                "type": "Clinic",
                "beds": 20,
                "services": ["General Medicine", "Pediatrics", "Dermatology"],
                "timings": "9:00 AM - 9:00 PM",
                "coordinates": { "lat": 28.5562, "lng": 77.2046 }
            },
            {
                "hospital_id": "H003",
                "name": "Sunrise Hospital",
                "address": "78 Sunrise Road, Ghaziabad",
                "pincode": "110001",
                "phone": "+91-9999988888",
                "email": "support@sunrisehospitals.com",
                "type": "Super-specialty",
                "beds": 300,
                "services": ["Neurology", "Nephrology", "Oncology", "ICU", "Emergency"],
                "timings": "24/7",
                "coordinates": { "lat": 28.6289, "lng": 77.2065 }
            },
            {
                "hospital_id": "H004",
                "name": "Life Line Hospital",
                "address": "23 Ashok Vihar, Delhi",
                "pincode": "110001",
                "phone": "+91-9898989898",
                "email": "lifeline@hospital.com",
                "type": "Multi-specialty",
                "beds": 200,
                "services": ["ENT", "Gastroenterology", "Orthopedics"],
                "timings": "24/7",
                "coordinates": { "lat": 28.6692, "lng": 77.1750 }
            },
            {
                "hospital_id": "H005",
                "name": "Hopewell Medical Center",
                "address": "Plot 54, Karol Bagh, Delhi",
                "pincode": "110001",
                "phone": "+91-9312345678",
                "email": "info@hopewellmed.com",
                "type": "Clinic",
                "beds": 35,
                "services": ["General Medicine", "Physiotherapy"],
                "timings": "10:00 AM - 6:00 PM",
                "coordinates": { "lat": 28.6507, "lng": 77.1909 }
            },

            {
                "hospital_id": "H006",
                "name": "Fortune Hospital",
                "address": "12 Block B, Noida Sector 62",
                "pincode": "201301",
                "phone": "+91-9123456789",
                "email": "contact@fortunehospital.com",
                "type": "Super-specialty",
                "beds": 250,
                "services": ["Cardiology", "Neurology", "ICU"],
                "timings": "24/7",
                "coordinates": { "lat": 28.6266, "lng": 77.3617 }
            },
            {
                "hospital_id": "H007",
                "name": "Noida City Clinic",
                "address": "A-34, Sector 15, Noida",
                "pincode": "201301",
                "phone": "+91-9876543219",
                "email": "noidaclinic@citymail.com",
                "type": "Clinic",
                "beds": 40,
                "services": ["Pediatrics", "Gynecology"],
                "timings": "8:00 AM - 8:00 PM",
                "coordinates": { "lat": 28.5933, "lng": 77.3178 }
            },
            {
                "hospital_id": "H008",
                "name": "Metro Medical Center",
                "address": "32 Metro Tower, Noida",
                "pincode": "201301",
                "phone": "+91-9000000001",
                "email": "metrocenter@health.com",
                "type": "Multi-specialty",
                "beds": 100,
                "services": ["Radiology", "Pathology", "General Surgery"],
                "timings": "24/7",
                "coordinates": { "lat": 28.5858, "lng": 77.3421 }
            },
            {
                "hospital_id": "H009",
                "name": "HealCare Hospital",
                "address": "Green Tower, Sector 50",
                "pincode": "201301",
                "phone": "+91-9000000002",
                "email": "healcare@hospital.org",
                "type": "Multi-specialty",
                "beds": 180,
                "services": ["Emergency", "Oncology"],
                "timings": "24/7",
                "coordinates": { "lat": 28.5668, "lng": 77.3558 }
            },
            {
                "hospital_id": "H010",
                "name": "Wellness Point",
                "address": "C-87, Sector 61",
                "pincode": "201301",
                "phone": "+91-9000000003",
                "email": "wellness@med.com",
                "type": "Clinic",
                "beds": 25,
                "services": ["Dentistry", "Skin Care"],
                "timings": "10:00 AM - 6:00 PM",
                "coordinates": { "lat": 28.6063, "lng": 77.3638 }
            },

            {
                "hospital_id": "H011",
                "name": "Ghaziabad Central Hospital",
                "address": "NH-24, Indirapuram, Ghaziabad",
                "pincode": "201010",
                "phone": "+91-9876512345",
                "email": "central@ghzbmed.com",
                "type": "Multi-specialty",
                "beds": 220,
                "services": ["ICU", "Emergency", "Cardiology"],
                "timings": "24/7",
                "coordinates": { "lat": 28.6414, "lng": 77.3601 }
            },
            {
                "hospital_id": "H012",
                "name": "Vivekanand Hospital",
                "address": "Plot 98, Vasundhara, Ghaziabad",
                "pincode": "201010",
                "phone": "+91-9876500001",
                "email": "vivek@hospital.com",
                "type": "Clinic",
                "beds": 30,
                "services": ["Physiotherapy", "General Medicine"],
                "timings": "8:00 AM - 4:00 PM",
                "coordinates": { "lat": 28.6692, "lng": 77.3539 }
            },
            {
                "hospital_id": "H013",
                "name": "Sarvoday Health Hub",
                "address": "B-76, Rajnagar Extension",
                "pincode": "201010",
                "phone": "+91-9876500002",
                "email": "sarvoday@medcenter.org",
                "type": "Super-specialty",
                "beds": 275,
                "services": ["ICU", "Oncology", "Neurology"],
                "timings": "24/7",
                "coordinates": { "lat": 28.6869, "lng": 77.3419 }
            },
            {
                "hospital_id": "H014",
                "name": "Dr. Khanna's Clinic",
                "address": "C-12, Patel Nagar",
                "pincode": "201010",
                "phone": "+91-9876500003",
                "email": "drkhanna@clinic.in",
                "type": "Clinic",
                "beds": 10,
                "services": ["ENT", "Skin Care"],
                "timings": "9:00 AM - 3:00 PM",
                "coordinates": { "lat": 28.6578, "lng": 77.3489 }
            },
            {
                "hospital_id": "H015",
                "name": "Care & Cure Hospital",
                "address": "87 Shakti Khand, Ghaziabad",
                "pincode": "201010",
                "phone": "+91-9876500004",
                "email": "carecure@hospital.in",
                "type": "Multi-specialty",
                "beds": 150,
                "services": ["Emergency", "General Surgery", "Radiology"],
                "timings": "24/7",
                "coordinates": { "lat": 28.6289, "lng": 77.3678 }
            },

            {
                "hospital_id": "H016",
                "name": "Nirman Medical Center",
                "address": "Sector 3, Rohini, Delhi",
                "pincode": "110085",
                "phone": "+91-9958000011",
                "email": "info@nirmanmed.in",
                "type": "Clinic",
                "beds": 50,
                "services": ["Gynecology", "General Medicine"],
                "timings": "9:00 AM - 5:00 PM",
                "coordinates": { "lat": 28.7041, "lng": 77.1025 }
            },
            {
                "hospital_id": "H017",
                "name": "Rohini Super Hospital",
                "address": "Plot 4, Rohini Sec 9",
                "pincode": "110085",
                "phone": "+91-9958000012",
                "email": "superrohini@hospital.com",
                "type": "Super-specialty",
                "beds": 300,
                "services": ["ICU", "Nephrology", "Oncology"],
                "timings": "24/7",
                "coordinates": { "lat": 28.7321, "lng": 77.1152 }
            },
            {
                "hospital_id": "H018",
                "name": "Sunbeam Hospital",
                "address": "Sunbeam Marg, Rohini",
                "pincode": "110085",
                "phone": "+91-9958000013",
                "email": "sunbeam@med.com",
                "type": "Multi-specialty",
                "beds": 170,
                "services": ["General Surgery", "Dermatology", "ENT"],
                "timings": "24/7",
                "coordinates": { "lat": 28.7195, "lng": 77.1089 }
            },
            {
                "hospital_id": "H019",
                "name": "Rohini Clinic Plus",
                "address": "B-23, Sector 7, Rohini",
                "pincode": "110085",
                "phone": "+91-9958000014",
                "email": "clinicplus@rohinihealth.in",
                "type": "Clinic",
                "beds": 15,
                "services": ["Pediatrics", "Dental"],
                "timings": "10:00 AM - 6:00 PM",
                "coordinates": { "lat": 28.7128, "lng": 77.1067 }
            },
            {
                "hospital_id": "H020",
                "name": "Rohini Family Health Center",
                "address": "B-67, Sec 8, Rohini",
                "pincode": "110085",
                "phone": "+91-9958000015",
                "email": "familycare@rohini.org",
                "type": "Clinic",
                "beds": 25,
                "services": ["General Medicine", "Diabetology"],
                "timings": "8:00 AM - 4:00 PM",
                "coordinates": { "lat": 28.7156, "lng": 77.1078 }
            },

            {
                "hospital_id": "H021",
                "name": "East Delhi Medcare",
                "address": "C-2 Yamuna Vihar",
                "pincode": "110053",
                "phone": "+91-9012345678",
                "email": "medcare@eastdelhi.com",
                "type": "Multi-specialty",
                "beds": 160,
                "services": ["Cardiology", "Neurology", "Emergency"],
                "timings": "24/7",
                "coordinates": { "lat": 28.7041, "lng": 77.2750 }
            },
            {
                "hospital_id": "H022",
                "name": "Yamuna PolyClinic",
                "address": "Block D, Yamuna Vihar",
                "pincode": "110053",
                "phone": "+91-9012345679",
                "email": "yamunapoly@clinic.com",
                "type": "Clinic",
                "beds": 30,
                "services": ["ENT", "Skin Care"],
                "timings": "9:00 AM - 5:00 PM",
                "coordinates": { "lat": 28.7089, "lng": 77.2789 }
            },
            {
                "hospital_id": "H023",
                "name": "Swasthya Hospital",
                "address": "E-5, Shahdara",
                "pincode": "110053",
                "phone": "+91-9012345680",
                "email": "swasthya@hospital.com",
                "type": "Multi-specialty",
                "beds": 130,
                "services": ["General Medicine", "ICU", "Radiology"],
                "timings": "24/7",
                "coordinates": { "lat": 28.6700, "lng": 77.2847 }
            },
            {
                "hospital_id": "H024",
                "name": "Delhi Heart Point",
                "address": "L-12, Krishna Nagar",
                "pincode": "110053",
                "phone": "+91-9012345681",
                "email": "heartpoint@delhihospital.com",
                "type": "Super-specialty",
                "beds": 280,
                "services": ["Cardiology", "Cardiac Surgery"],
                "timings": "24/7",
                "coordinates": { "lat": 28.6667, "lng": 77.2734 }
            },
            {
                "hospital_id": "H025",
                "name": "Shakti Clinic",
                "address": "E-89, Yamuna Vihar",
                "pincode": "110053",
                "phone": "+91-9012345682",
                "email": "shakticlinic@health.org",
                "type": "Clinic",
                "beds": 12,
                "services": ["General Checkup", "Diabetology"],
                "timings": "10:00 AM - 4:00 PM",
                "coordinates": { "lat": 28.7156, "lng": 77.2823 }
            }
        ]
    },

    getHospitalList(pincode) {
        return Promise.resolve(
        this.getHospitals().filter(hospital => hospital["pincode"] === pincode)
        );
    }
}
